### ISSUE TITLE
ESS per wall clock time

### ISSUE THREAD

**Issue by JohannesBuchner** [mattpitkin/samplers-demo#17]
Hi @mattpitkin 

This is a great page https://mattpitkin.github.io/samplers-demo/pages/samplers-samplers-everywhere/

It would be useful to also mention the number of likelihood evaluations and the effective sample size (ESS). In particular the ESS per wall clock time is the standard for comparing the efficiency of samplers. Here the ESS per number of likelihood evaluations could also be interesting.

You can find the function to compute the ESS here: https://fredros.github.io/pypmc/html/tools.html?highlight=ess#pypmc.tools.convergence.ess . That formula gives the fraction of effective samples, for the number of effective samples multiply by N.

You can keep track of the number of likelihood calls with this neat python trick of attaching properties to functions:

```
def myfunc(params):
     myfunc.ncalls += 1
     # do stuff

myfunc.ncalls = 0

# do stuff with myfunc...

# then:
print(myfunc.ncalls)
```

**Comment by mattpitkin** [comment]
Hi @JohannesBuchner, thanks for the tip. I will look into adding this the next time I get round to updating the page.

**Comment by mattpitkin** [comment]
Hi @JohannesBuchner, I'm *finally* getting round to doing some updates of the webpage and am thinking about adding ESS. I was just wondering what exactly the `weights` input to the pypmc [ess](https://fredros.github.io/pypmc/html/tools.html#pypmc.tools.convergence.ess) function should be. Can it just be the posterior probability density values for each sample? So, for example, if I'd run emcee and returned the EnsembleSampler as `sampler`, could I just do something like:

```python
def effective_sample_size(weights):
    """
    Weights is the posterior probability density for each sample.
    """

    normweights = weights / np.sum(weights)
    N = len(weights)
    csquared = np.mean((N * normweights - 1)**2)
    ess = N / (1 + csquared)

    return ess

# weight from emcee posterior values
weights = np.exp(sampler.lnprobability.flatten() - np.max(sampler.lnprobability.flatten()))
essemcee = effective_sample_size(weights=weights)
```

or is this not what is meant by the weights?

**Comment by JohannesBuchner** [comment]
No, for MCMC you would compute the ESS using the autocorrelation length formula. For nested and importance sampling, you can use the weight formula.

**Comment by JohannesBuchner** [comment]
https://www.johndcook.com/blog/2017/06/27/effective-sample-size-for-mcmc/ 

Essentially:
```ESS = len(chain) / emcee.autocorr.integrated_time(args)```
but you need to catch AutocorrError if chain is too short (meaning ESS=0).

**Comment by JohannesBuchner** [comment]
For the autocorr time, I would recommend you compute it for each parameter and each walker and take the maximum of that to be conservative.

**Comment by JohannesBuchner** [comment]
I have some code that does this computation here: https://github.com/JohannesBuchner/autoemcee/ which you can reuse.

**Comment by JohannesBuchner** [comment]
For nested sampling, in UltraNest I implemented the weight formula here: https://github.com/JohannesBuchner/UltraNest/blob/master/ultranest/integrator.py#L1091

**Comment by mattpitkin** [comment]
@JohannesBuchner great, thanks very much
