### ISSUE TITLE
Update to UltraNest 2

### ISSUE THREAD

**Issue by JohannesBuchner** [mattpitkin/samplers-demo#29]
Hi, could you please update the UltraNest demo, instead of the ancient one in nested_sampling package

Tutorials, API etc. can be found here: https://johannesbuchner.github.io/UltraNest/

**Comment by mattpitkin** [comment]
Sure! In fact, I've just done this and update the page a few minutes ago. The updated Ultranest demo can be found in the main page [here](http://mattpitkin.github.io/samplers-demo/pages/samplers-samplers-everywhere/#UltraNest), or as the standalone example [here](http://mattpitkin.github.io/samplers-demo/pages/ultranest/).

**Comment by JohannesBuchner** [comment]
Ah, sorry, I looked at it when I got the github notification, and got the old page. Thanks!

**Comment by mattpitkin** [comment]
No problem. I'd literally just updated it.
